# Generated by Django 3.2.4 on 2021-07-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
    ]
